apiVersion: v2
name: libretranslate
description: Libretranslate Helm chart for Kubernetes
icon: https://f3k-tech.github.io/helm/icons/libretranslate.png
type: application
version: 1.165.0
appVersion: v1.6.5
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: bumped container image to version 1.6.5
maintainers:
  - name: FreekO
    email: info@f3k.tech
