{{- if .Values.frontend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "atlas-cmms.serviceAccountName-frontend" . }}
  labels:
    {{- include "atlas-cmms.labels" . | nindent 4 }}
  {{- with .Values.frontend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.frontend.serviceAccount.automount }}
{{- end }}
