{{- if .Values.persistence.data.enabled -}}
{{- if not .Values.persistence.data.existingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "cap-captcha-server.fullname" . }}-data
  labels:
    app.kubernetes.io/name: {{ include "cap-captcha-server.name" . }}
    helm.sh/chart: {{ include "cap-captcha-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: app
{{- if .Values.persistence.data.annotations }}
  annotations:
{{ toYaml .Values.persistence.data.annotations | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
{{- if .Values.persistence.data.storageClass }}
{{- if (eq "-" .Values.persistence.data.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.data.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}