apiVersion: v2
name: recaptcha-v3-verifier
description: A Helm chart for Kubernetes to deploy a reCAPTCHA v3 verification service
type: application
version: 1.110.0
appVersion: "1.1.0"
icon: https://f3k-tech.github.io/helm/icons/recaptcha-v3.jpg
maintainers:
  - name: FreekO
    email: info@f3k.tech
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: bumped container image to version 1.1.0
    - kind: changed
      description: added support for multi-account configuration via environment variables
  artifacthub.io/links: |
    - name: support
      url: https://github.com/f3k-tech/helm/issues