apiVersion: v2
name: recaptcha-v3-verifier
description: A Helm chart for Kubernetes to deploy a reCAPTCHA v3 verification service
type: application
version: 1.100.0
appVersion: "1.0.0"
icon: https://f3k-tech.github.io/helm/icons/recaptcha-v3.jpg
maintainers:
  - name: FreekO
    email: info@f3k.tech