apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "akaunting.fullname" . }}
  labels:
    {{- include "akaunting.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "akaunting.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "akaunting.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "akaunting.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: download-configs
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache wget && \
              until wget -q -O /config/nginx.conf https://github.com/akaunting/docker/raw/refs/heads/master/nginx/nginx.conf && \
                    wget -q -O /config/php.ini https://github.com/akaunting/docker/raw/refs/heads/master/files/php.ini && \
                    wget -q -O /config/supervisord.conf https://github.com/akaunting/docker/raw/refs/heads/master/files/supervisord.conf; do
                echo "Failed to download files, retrying in 5 seconds..." >&2
                sleep 5
              done
          volumeMounts:
            - name: config-volume
              mountPath: /config
        - name: download-application-files
          image: alpine:latest
          {{- if .Values.env }}
          env:
            {{- .Values.env | toYaml | nindent 12 }}
          {{- end }}
          command:
            - /bin/sh
            - -c
            - |
              if [ "$AKAUNTING_UPGRADE" == "true" ]; then
                apk add --no-cache curl unzip && \
                curl -Lo /tmp/akaunting.zip 'https://github.com/akaunting/akaunting/releases/download/{{ .Chart.AppVersion }}/Akaunting_{{ .Chart.AppVersion }}-Stable.zip' && \
                unzip -o /tmp/akaunting.zip -d /var/www/html && \
                rm -f /tmp/akaunting.zip
              else
                echo "Skipping application download as AKAUNTING_UPGRADE is not true.";
              fi
          volumeMounts:
            - name: akaunting-data
              mountPath: /var/www/html
        - name: wait-for-mariadb
          image: busybox
          command:
            - sh
            - "-c"
            - |
              until nc -zv {{ template "akaunting.fullname" . }}-mariadb 3306; do
                echo "Waiting for MariaDB to be ready...";
                sleep 2;
              done
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}{{- if .Values.image.flavour }}-{{ .Values.image.flavour }}{{- end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ include "akaunting.fullname" . }}-mariadb
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: {{ .Values.mariadb.auth.database }}
            - name: DB_USERNAME
              value: {{ .Values.mariadb.auth.username }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "akaunting.fullname" . }}-mariadb
                  key: mariadb-password
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "akaunting.fullname" . }}-secret
                  key: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "akaunting.fullname" . }}-secret
                  key: ADMIN_PASSWORD
            {{- if .Values.env }}
            {{- .Values.env | toYaml | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args: {{ .Values.args | toYaml | nindent 12 }}
          volumeMounts:
            - name: akaunting-data
              mountPath: /var/www/html
            - name: config-volume
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            - name: config-volume
              mountPath: /etc/supervisor/conf.d/supervisord.conf
              subPath: supervisord.conf
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: akaunting-data
          {{- if .Values.persistence.data.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.data.existingClaim }}{{ .Values.persistence.data.existingClaim }}{{- else }}{{ template "akaunting.fullname" . }}-data{{- end }}
          {{- end }}
        - name: config-volume
          emptyDir: {}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
