apiVersion: v2
name: cap-captcha-server
description: Lightweight, privacy-first, and open-source CAPTCHA server for the modern web.
icon: https://f3k-tech.github.io/helm/icons/cap.png
type: application
version: 0.21.0
appVersion: "2.1"
maintainers:
  - name: FreekO
    email: info@f3k.tech
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: initial chart version 0.21.0 deploying cap-captcha-server version 2.1
  artifacthub.io/links: |
    - name: Issues
      url: https://github.com/f3k-tech/helm/issues